name: enlabtest
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  html_unescape: ^2.0.0
  http: ^0.13.6
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/1024.png"
  adaptive_icon_foreground: "assets/1024.png"
  adaptive_icon_background: "assets/1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
 